### PR TITLE
Cookbook testing

### PR DESCRIPTION
**Pull request by motns**
First of all, I'd like to apologize for the size of the pull request - if you don't want to merge it, I understand (no hard feelings).
I really liked the simplified approach that you took with this cookbook (especially the nice and clean config files), so I decided to base our new infrastructure on it, as opposed to using the official Opscode php cookbook.

My original intention was to make a few small fixes, and more importantly add some tests to make sure things work. The unit and integration tests that I added flagged a number of issues with the existing code, and so I went ahead and put in fixes for those, at which point things got a little out of hand... :P

**Summary of changes**
- Tests
  - Added unit tests via Strainer, which runs `knife test` for a basic syntax check, followed by Foodcritic for linting. These tests also work in Travis CI, so you can add a shiny build badge to your Readme if you like! ;)
  - Added integration tests via Opscode's Test Kitchen (1.0 alpha release). These will converge all the recipes on a number of platforms (Ubuntu, CentOS, Debian), and then run a number of tests to verify the state of the machine. These will only run on your local workstation.
- Syntax fixes
  - The Foodcritic test flagged a number of "violations", so I took the liberty and lined those up with current best practices.
- Platform support
  - I noticed that you listed pretty much all available platforms in the `metadata.rb` file, but when running the integration tests I found that the recipes were broken on most of them. Again, I went ahead and fixed these where it was possible. I also updated the Readme and metadata to reflect the actual compatibility.
- Customisation
  - I added a few more configurable options to both the `php.ini` files, and the php-fpm configurations.

You can find a short overview about the tests on our Readme page [here](https://github.com/hipsnip-cookbooks/cookbook-development).

We don't really want to maintain a separate fork of your repo, so it would be really nice if we could get these changes back to your somehow. I'm happy to talk you through the tests in more detail, and maybe break down the changes into more manageable chunks.

### CODE REVIEW

**Comment by joelwurtz** [comment]
animation3

Hey,

First of all, huge thanks for this PR i didn't know about strainer seems to work like a charm and really like it. Just to be sure there is only syntax checks and foodcritic currently ?

Otherwise, all updates seems good to me, but due to replacment of php fpm definition by a LWRP i will release a 1.1.0 version to not break BC for people already using this cookbook. 

I will also add a pgsql recipe before upgrade version, review other PR and update CHANGELOG (should be done today).

For plateform i was a little bit optimist :), it was mainly tested on debian dotdeb platform and checked at hand for others. With integration test this should be easier now.

Thanks again !

**Comment by motns** [comment]
Thanks for merging this in - it's very much appreciated!

Correct, Strainer is only running syntax checks at the moment - you can see the commands in the `Strainerfile` in the root. However it's basically a workflow tool for cookbook testing, so you can add other commands as well.

Another tool that can go in a Strainer workflow is [Chefspec](https://github.com/acrmp/chefspec). It basically executes your recipes in a "simulated" chef run, and then lets you inspect and verify the results via Rspec-based tests. The advantage is that you can run these without a VM, so they are very fast, and can also be executed even in Travis CI. The downside is that you'll often duplicate some of your tests between Chefspec and Test Kitchen. See, Chefspec can only test whether or not you told Chef to do something in your recipe, whereas Test Kitchen will actually execute that recipe on a server, and verify that the end result is as intended.

For a working example, you can have a look at our Jetty cookbook [here](https://github.com/hipsnip-cookbooks/jetty):
- The `Strainer` file has an extra entry for chefspec
- The `specs` folder contains the Chefspec tests to run
- The `test` folder has all the Test Kitchen tests

I left out the chefspec tests on the first run, because I didn't want things to look too confusing - I already made way too many changes for you to look through! But I'd be more than happy to get the ball rolling on those, if you're interested.

As for the platform testing: I figured from the code that you're usig this cookbook on Debian, so I added a test suite specifically for Debian with Dotdeb to make sure I didn't break anything for you (Opscode only tests Ubuntu and CentOS officially). Still, I don't know how closely I matched your configuration in the test, so please double-check! I also couldn't add tests for the "zeromq" recipe, because it depends on ZeroMQ being installed on the box when the recipe runs; again, if you use this please double-check.

Thanks again for merge!

**Comment by joelwurtz** [comment]
I'm currently adding a test for zeromq, for dotdeb i have checked and it works no worry. 

If you want to add chefspecs sure do it, like you said many people do chefspecs as they were integration test (and many tests are just testing chef) I'm interested in how you do them. 

In my view i prefer Test Kitchen which is more close to our brain when we think "test", although it's way longer to run.

**Comment by motns** [comment]
I'm totally with you on Test Kitchen - it is as accurate as testing gets, so it's always the best place to start.

The argument for chefpsec is that it allows you to iterate much faster, and catch early mistakes without costly test runs. Also - and this is the cool bit - if you set up a build for your repo in Travis CI, every time someone submits a pull request, it will be automatically tested, and the result displayed on the pull request page!

I'll get the ball rolling on some basic specs then, and we can take it from there.

**Comment by joelwurtz** [comment]
Yes, i totally agree.

Setup for travis ci is done, thanks for your time on tests. If you set up some basics tests witch Chefspec i will try to get some times to do them on existing recipes.

I will update cookbook on chef community site later today if you are interested

**Pull request merged**
